repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # -   id: check-added-large-files
      #     args: ['--maxkb=25']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: check-yaml
        exclude:  |
            (?x)^(
                environment.yml|
                .pre-commit-config.yaml
            )$
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: text-unicode-replacement-char
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.1
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
    -   id: docformatter
        args: [--in-place, --wrap-summaries, "88", --wrap-descriptions, "88", --blank]
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-alfred,
            flake8-bugbear,
            flake8-builtins,
            flake8-comprehensions,
            flake8-docstrings,
            flake8-eradicate,
            flake8-print,
            flake8-pytest-style,
            flake8-todo,
            flake8-typing-imports,
            flake8-unused-arguments,
            pep8-naming,
            pydocstyle,
            Pygments,
        ]
        exclude: (server|conf\.py)
        args: ["--ignore=D100,D103,D104"]
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
    -   id: mdformat
        additional_dependencies: [
            mdformat-gfm,
            mdformat-black,
        ]
        args: [--wrap, "88"]
        files: (README\.md)
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        exclude: ^.*\.ipynb$
-   repo: https://github.com/guilatrova/tryceratops
    rev: v1.1.0
    hooks:
    -   id: tryceratops
        exclude: (server|pyproject\.toml)
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
