name: scai

channels:
  - conda-forge
  - plotly
  - nodefaults
  - pytorch
  - huggingface

dependencies:
  - python >= 3.9
  - pip
  - conda-build

  - jupyterlab
  - ipython
  - ipdb
  - pdbpp
  - pytest
  - click == 8.0.4

  - pytask
  - pytask-latex

  - pandas
  - numpy
  - scikit-learn
  - plotly

  - flake8
  - nb_black

  # - cudatoolkit=11.7

  # from https://tinyurl.com/bdejspmd
  - accelerate
  - pytorch >= 1.3
  - datasets >= 1.8.0
  - sentencepiece != 0.1.92
  - protobuf
  - pip:
      - evaluate
      - git+https://github.com/huggingface/transformers
      - black
      - blackcellmagic
      - pre-commit
      - -e .
