name: aimee

channels:
  - conda-forge
  - plotly
  - defaults

dependencies:
  - python=3.9
  - conda-build

  - jupyterlab

  - pandas
  - numpy
  - plotly
  - scikit-learn

  - pytest
  - pytask
  - pytask-latex

  - flake8

  - pip
  - pip:
      - git+https://github.com/Breakend/experiment-impact-tracker
        # - experiment-impact-tracker
      - scikeras
      - tensorflow
      - black
      - blackcellmagic
      - pre-commit
