name: scai

channels:
  - conda-forge
  - plotly
  - pytorch
  - defaults

dependencies:
  - python >= 3.9
  - conda-build

  - jupyterlab
  - ipython
  - ipdb
  - pdbpp
  - pytest

  - pytask
  - pytask-latex

  - pandas
  - numpy
  - scikit-learn
  - plotly

  - flake8
  - nb_black

  - pip
  - pip:
      - black
      - blackcellmagic
      - pre-commit
      - -e .
