name: aimee

channels:
  - conda-forge
  - plotly
  - pytorch
  - defaults

dependencies:
  - python=3.9
  - conda-build

  - jupyterlab

  - pandas
  - numpy
  - scikit-learn
  - plotly

  - transformers
  - sentencepiece
  - pytorch-cpu
  - torchvision-cpu

  - pytest
  - pytask
  - pytask-latex

  - flake8
  - nb_black

  - pip
  - pip:
      - black
      - blackcellmagic
      - pre-commit
