name: bert

channels:
    - conda-forge
    - nodefaults
    - pytorch
    - huggingface

dependencies:
    - python >= 3.9
    - pip

    - pytask >= 0.2
    - pandas
    - numpy
    - scikit-learn

    - jupyterlab
    - ipython
    - pytest
    - pdbpp
    - ipdb

    - cudatoolkit=11.7

    # from https://tinyurl.com/bdejspmd
    - accelerate
    - pytorch >= 1.3
    - datasets >= 1.8.0
    - sentencepiece != 0.1.92
    - protobuf
    - pip:
      - evaluate
      - git+https://github.com/huggingface/transformers
